# -*- coding: utf-8 -*-
"""assignment1_0514.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_8TCzMz7Vl2X9B00PUpelamXZiHSMzo
"""

#Second Largest Element
ls=[int(x) for x in input("Enter list of numbers:").split()]
print(ls)
largest=float('-inf')
slargest=float('-inf')
for x in ls:
  if x>largest:
    slargest=largest
    largest=x
  elif x>slargest and x!=largest:
    slargest=x
if(slargest==float('-inf')):
  print("no second largest number!")
else:
  print("second largest=",slargest)

l1=[int(x) for x in input("Enter list of numbers:").split()]
dict={}
for x in l1:
  if x in dict:
    dict[x]+=1
  else:
    dict[x]=1
print("frequency of each number:",dict)